### ISSUE TITLE
typo in the README.md "Usage with Node" code

### ISSUE THREAD

**Issue by ghost** [gr2m/uscis-service-center-processing-times#1]
At line 1, it should be `const` not `cost`

**Comment by gr2m** [comment]
would you like to send a pull request for it? Let me know if you need any guidance, happy to walk you trough

**Comment by ghost** [comment]
Just submitted the pull request. 
Would like to contribute more to this project! :)

**Comment by gr2m** [comment]
yay thanks! So it, and closing this issue via https://github.com/gr2m/uscis-service-center-processing-times/pull/2

And also yay, you are more than welcome to contribute more. Feel free to comment on this issue with more questions or create new issues with suggestions on what you’d like to work on :)

For example, we could add some kind of loading bar to the `uscis-service-center-processing-times` CLI tool, to let people know that something is happening?

Another idea would be to create markdown files for all the processing times in this repository and then update them via the cron job on Travis. That way we start building up a dataset with history and other folks could use that to see how velocity changes over time, for example :)
